add messages on set-ip-to-host

diff --git a/bin/set-ip-to-host b/bin/set-ip-to-host
--- a/bin/set-ip-to-host
+++ b/bin/set-ip-to-host
@@ -15,10 +15,18 @@ mkdir -p "$DIR_WSL_PFM"
 mkdir -p "$DIR_DISTRO"
 
 c_ip=$(ip a show eth0 | grep -w -m1 inet | awk '{print $2}' | awk -F'/' '{print $1}')
+if [[ -z "$c_ip" ]]; then
+    echo "Error: Failed to get the current IP address." 1>&2
+    exit 1
+fi
+
 saved_ip=""
 if [[ -e "$DIR_DISTRO/ip" ]]; then
     saved_ip=$(cat "$DIR_DISTRO/ip")
 fi
 if [[ "$c_ip" != "$saved_ip" ]]; then
     echo -n "$c_ip" > "$DIR_DISTRO/ip"
+    echo "Refreshed IP address to '$c_ip'."
 fi
+
+exit 0
